// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxzdjoycwlflnjseomrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4emRqb3ljd2xmbG5qc2VvbXJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NTkxNDEsImV4cCI6MjA1MzEzNTE0MX0.u8No_6o1Q0n-PlHh9nIKnmSmd8ctiKk8UjqQX5spAlE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);